#pragma config(Motor,  port1,           motorY1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motorX2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           motorX1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motorY2,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Global Variable Defs
//////////////////////
//Drive
int driveX = 0; 			//X-axis Drive
int driveY = 0; 			//Y-axis Drive
int turn = 0;					//Turn Power & Arc Control
int deadbandMID = 10;	//Anti-Drift Origin Deadband

task main()
{
	while (true) { //LOOP fuction

		//Initial Deadband App [JOY => Var]
		if (abs(vexRT[Ch4]) > deadbandMID) {	//Ch4 => driveX
			driveX = (vexRT[Ch4]);
			} else {
			driveX = 0;
		}
		if (abs(vexRT[Ch3]) > deadbandMID) {	//Ch3 => driveY
			driveY = (vexRT[Ch3]);
			} else {
			driveY = 0;
		}
		if (abs(vexRT[Ch1]) > deadbandMID) {	//Ch1 => turn
			turn = (vexRT[Ch1]);
			} else {
			turn = 0;
		}

		//Drive Motor Actuation [Var => Motor]
		motor[motorY1] = (driveY + turn);
		motor[motorY2] = (driveY - turn);
		motor[motorX1] = (driveX + turn);
		motor[motorX2] = (driveX - turn);
	}
}
