#pragma config(Motor,  port1,           motorY1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motorX2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           launch1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           launch2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           launch3,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           launch4,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motorY2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           motorX1,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1) {
		motor[motorY1] = (vexRT[Ch3] + vexRT[Ch1]);
		motor[motorY2] = (vexRT[Ch3] - vexRT[Ch1]);
		motor[motorX1] = (vexRT[Ch4] + vexRT[Ch1]);
		motor[motorX2] = (vexRT[Ch4] - vexRT[Ch1]);
	}
}
